# Generated by Django 5.1.2 on 2024-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_appointment_date_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
