# Generated by Django 5.1.2 on 2024-11-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teammember', verbose_name='Мастер')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Временное окно',
                'verbose_name_plural': 'Временные окна',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
