# Generated by Django 5.1.2 on 2024-11-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_timeslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='classification',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Классификация'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
