# Generated by Django 5.1.2 on 2024-11-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_review_options_alter_teammember_options_and_more'),
    ]

    operations = [
    ]
