# Generated by Django 5.1.2 on 2024-11-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_portfoliowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Фото'),
        ),
    ]
